### ISSUE TITLE
(Spring Boot) Cannot construct instance of `com.yubico.webauthn.data.AuthenticatorAttestationResponse`

### ISSUE THREAD

**Issue by mommi2** [Yubico/java-webauthn-server#165]
**Versions**
```
spring: 4.0.5.RELEASE
webauthn-server-core: 1.12.1
```

Hi, 
i have the following issue with webauthn-server-core while a performe finish registrations
```
Cannot construct instance of `com.yubico.webauthn.data.AuthenticatorAttestationResponse`, problem: com.fasterxml.jackson.dataformat.cbor.CBORFactory._createContentReference(Ljava/lang/Object;II)Lcom/fasterxml/jackson/core/io/ContentReference;
 at [Source: (String)"{
    "type": "public-key",
    "id": "Wg6aYnz8i3q8WmUKxA0q79aVusYjifvUy4ACR_u1SCc",
    "response": {
        "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVkBZ0mkMTVTmQi5mT9Ym3Xoh1wDChI_iZu8WRJZl1Mkxyz5RQAAAAAAAAAAAAAAAAAAAAAAAAAAACBaDppifPyLerxaZQrEDSrv1pW6xiOJ-9TLgAJH-7VIJ6QBAwM5AQAgWQEA4Ug0uMWL0OWbe0gOgjxBcsKAm2JhSykamdPpqcWFdKnDlG3NDuLanJX6keUzLrQSJcgU3ICk2zs2-eDUK0xbakxhJ0dK3gT1-Qu2c9IPKgfmE9HgA2bMltk-EWFmdXs5lMOKv_mPy9YSya2YZNpz5IWlS3HSscgndMt3H-ySSi2yu_a0vshaSSHHVuI5l2f"[truncated 528 chars]; line: 10, column: 5] (through reference chain: com.yubico.webauthn.data.PublicKeyCredential["response"])
```
```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.cbor.CBORFactory._createContentReference(Ljava/lang/Object;II)Lcom/fasterxml/jackson/core/io/ContentReference;
        at com.fasterxml.jackson.dataformat.cbor.CBORFactory.createParser(CBORFactory.java:336) ~[jackson-dataformat-cbor-2.13.1.jar:2.13.1]
        at com.fasterxml.jackson.dataformat.cbor.CBORFactory.createParser(CBORFactory.java:330) ~[jackson-dataformat-cbor-2.13.1.jar:2.13.1]
        at com.fasterxml.jackson.dataformat.cbor.CBORFactory.createParser(CBORFactory.java:27) ~[jackson-dataformat-cbor-2.13.1.jar:2.13.1]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2572) ~[jackson-databind-2.9.10.jar!/:2.9.10]
        at com.yubico.webauthn.data.AttestationObject.<init>(AttestationObject.java:104) ~[webauthn-server-core-minimal-1.12.0.jar:1.12.0]
        at com.yubico.webauthn.data.AuthenticatorAttestationResponse.<init>(AuthenticatorAttestationResponse.java:112) ~[webauthn-server-core-minimal-1.12.0.jar:1.12.0]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_261]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_261]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_261]
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124) ~[jackson-databind-2.9.10.jar!/:2.9.10]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283) ~[jackson-databind-2.9.10.jar!/:2.9.10]
        ... 120 more
```

The error came up with the following code:
```
PublicKeyCredential<AuthenticatorAttestationResponse, ClientRegistrationExtensionOutputs> pkc = PublicKeyCredential
		.parseRegistrationResponseJson(publicKeyCredentialJson);
```

**Comment by emlun** [comment]
Hi! I'm not sure what's wrong here, but `NoSuchMethodError` usually indicates some kind of classpath issue. Just a wild guess, but: it looks like you have different versions of `jackson-databind` (2.9.10) and `jackson-dataformat-cbor` (2.13.1), maybe that could have something to do with it?

**Comment by mommi2** [comment]
Hi, as you suggested it was a mismatch problem between libraries. Thanks for the support and availability

**Comment by emlun** [comment]
Great, I'm glad I could help! I'll close this issue then, you're welcome to re-open it if there's anything else you need.
