### ISSUE TITLE
Postgres Database Incompatibility 

### ISSUE THREAD

**Issue by aasemani** [Yubico/java-webauthn-server#251]
I am trying to use a Postgres instead of the H2 DB for my application. When switching to Postgres DB I get errors relating to column type. I have tried multiple different types such as OID, VARCHAR, BIGINT,... . 
Is the application compatible with Postgres? What are the databases I can use other than H2 for the passkey to work?

`java.lang.IllegalArgumentException: Parameter value [ByteArray(0b1a119b1c68f9756e3b0046d49bb46c06ec99759153439a3c40a7ee9075dbb1)] did not match expected type [[B (n/a)]
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:54) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:27) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.query.internal.QueryParameterBindingImpl.validate(QueryParameterBindingImpl.java:90) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
`

**Comment by aasemani** [comment]
@emlun thank you for the help. I was able to get it working by converting all the `ByteArray` variables to string and saving them as varchar in database. Also needed to remove `@lob` annotation.
