### ISSUE TITLE
NPE @ FinishRegistrationStep.Step22.validate

### ISSUE THREAD

**Issue by fcorneli** [Yubico/java-webauthn-server#324]
In case `credentialRepository.lookupAll` returns a `null`.
Stack trace:
```
Caused by: java.lang.NullPointerException
	at com.yubico.webauthn.FinishRegistrationSteps$Step22.validate(FinishRegistrationSteps.java:620)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.next(FinishRegistrationSteps.java:113)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:121)
	at com.yubico.webauthn.FinishRegistrationSteps.run(FinishRegistrationSteps.java:100)
	at com.yubico.webauthn.RelyingParty.finishRegistration(RelyingParty.java:505)
```

**Comment by emlun** [comment]
If no credentials are found, `CredentialRepository.lookupAll` should return an empty set, not `null`.
