### ISSUE TITLE
NullPointerException at finishRegistration

### ISSUE THREAD

**Issue by fkoepke** [Yubico/java-webauthn-server#65]
Hi,

in my finishRegistration method I run following to build the FinishRegistrationOptions to put it in finishRegistration Method of the RelyingParty. But in the debugger the value of callerTokenBindingId of the FinishRegistrationOptions is null.
```
FinishRegistrationOptions finishRegistrationOptions = FinishRegistrationOptions.builder()
        .request(startResponse.getPublicKeyCredentialCreationOptions())
        .response(finishRequest.getCredential())
        .build();
```

When I call finishRegistration of RelyingParty with the finishRegistrationOptions above I get following exception:
```
java.lang.NullPointerException: null
	at com.yubico.webauthn.FinishRegistrationSteps$Step17.validate(FinishRegistrationSteps.java:622) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.next(FinishRegistrationSteps.java:115) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps$Step.run(FinishRegistrationSteps.java:123) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.FinishRegistrationSteps.run(FinishRegistrationSteps.java:89) ~[webauthn-server-core-1.6.2.jar:1.6.2]
	at com.yubico.webauthn.RelyingParty.finishRegistration(RelyingParty.java:444) ~[webauthn-server-core-1.6.2.jar:1.6.2]
```

My Problem is, I can't find in the documentation if I have to set this value for callerTokenBindingId and where I have to set it.

<details>
  <summary>Response of startRegistration I get in client</summary>
  
```
{
  "status": "OK",
  "registrationId": "pshpETxYtI8HNlqMTB+7fw==",
  "publicKeyCredentialCreationOptions": {
    "rp": {
      "name": "Example Application",
      "id": "localhost"
    },
    "user": {
      "name": "Testname",
      "displayName": "TestDisplayName",
      "id": "AAAAAAAAADQ"
    },
    "challenge": "9XiroqI145r5KeeSy8RJBvPQ-41ALbQClQwDBQAYQJk",
    "pubKeyCredParams": [
      {
        "alg": -7,
        "type": "public-key"
      },
      {
        "alg": -8,
        "type": "public-key"
      },
      {
        "alg": -257,
        "type": "public-key"
      }
    ],
    "excludeCredentials": [],
    "attestation": "none",
    "extensions": {}
  }
}
```
</details>

<details>
  <summary>Credential after calling create in client</summary>

```
{
  "type": "public-key",
  "id": "AdBKv_pk2sbNIwH3odb5i7ENY3dUvPIoSt1Z5_ZX1WB4DxQz9nlLW...",
  "rawId": "AdBKv_pk2sbNIwH3odb5i7ENY3dUvPIoSt1Z5_ZX1WB4DxQz9nlLW...",
  "response": {
    "clientDataJSON": "eyJjaGFsbGVuZ2UiOiI5WGlyb3FJMTQ1cjVLZWVTeThSSkJ2UFEtNDFB...",
    "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVjFSZYN5YgOjG..."
  },
  "clientExtensionResults": {}
}
```
</details>

<details>
  <summary>Credential Response I send back to server for finishRegistration</summary>

```
{
  "registrationId": "pshpETxYtI8HNlqMTB+7fw==",
  "credential": {
    "type": "public-key",
    "id": "AdBKv_pk2sbNIwH3odb5i7ENY3dUvPIoSt1Z5_ZX1WB4DxQz9nlLW...",
    "rawId": "AdBKv_pk2sbNIwH3odb5i7ENY3dUvPIoSt1Z5_ZX1WB4DxQz9nlLW...",
    "response": {
      "clientDataJSON": "eyJjaGFsbGVuZ2UiOiI5WGlyb3FJMTQ1cjVLZWVTeThSSkJ2UFEtNDFB...",
      "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVjFSZYN5YgOjG..."
    },
    "clientExtensionResults": {}
  }
}
```
</details>

**Comment by emlun** [comment]
Hi!

Don't worry about the `calledTokenBindingId`, that's for WebAuthn's optional [Token Binding](https://w3c.github.io/webauthn/#dom-collectedclientdata-tokenbinding) support. As far as I know, Token Binding has fallen out of favour in some of the major browsers and isn't really used anywhere at this time.

It rather looks like your `CredentialRepository.lookupAll(ByteArray credentialId)` implementation might be returning `null`. Please make sure that you return an empty `Set` if there are no credentials with the given credential ID in the database.

**Comment by fkoepke** [comment]
Thank you @emlun. This was my mistake. I didn't see that the library checks for credentials when I want to register a new one.
That solves my problem.

**Comment by emlun** [comment]
Glad to help!

**Comment by ericteles54hotmail** [comment]
I have a similar problem.

The options json is this
{"rp":{"name":"My First Example Application","id":"example.com"},"user":{"name":"test","displayName":"Display name - test","id":"YzU4Mzk5NDMtYzUxMy00MWQ0LWFiMWYtZjdmYmVmZTIwMjli"},"challenge":"KoZZZtghET7_UNnuQsMJVnZ4jhUfnNSp8aU4qFku1AQ","pubKeyCredParams":[{"alg":-7,"type":"public-key"},{"alg":-35,"type":"public-key"},{"alg":-36,"type":"public-key"},{"alg":-257,"type":"public-key"},{"alg":-258,"type":"public-key"},{"alg":-259,"type":"public-key"}],"timeout":60000,"excludeCredentials":[],"authenticatorSelection":{"authenticatorAttachment":"cross-platform","userVerification":"discouraged"},"attestation":"none","extensions":{"credProps":true}}

After navigator.credentials.create I send this json to backend
{"id":"lUhDioNwIDWJvBivAT3Phw","rawId":"lUhDioNwIDWJvBivAT3Phw","type":"public-key","response":{"attestationObject":"o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YViUsxd3sRAhhKefapdkrjrWf1FZZbY86efnPuD_BiksonZdAAAAAAAAAAAAAAAAAAAAAAAAAAAAEJVIQ4qDcCA1ibwYrwE9z4elAQIDJiABIVggX8VV988zvrbQmtusVM3LN027Rlr4fSPMVdfk_WBv8MEiWCAuLgyeOJaro_v5hO64Lz66oKiv1oFF_SRsujKbfR2oww","clientDataJSON":"eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiQUFBQUFBQUFBQUFBQUFjQUFBQUFBQUFBQUFBQUFBQUVBQUFBQUFBQUFBQUlBQUFFQUFBQUFBRUFBQSIsIm9yaWdpbiI6Imh0dHBzOi8vbG9naW4udXRvcGlhLm5vdmVsbC5jb206ODQ0MyIsImNyb3NzT3JpZ2luIjpmYWxzZX0"},"clientExtensionResults":{"credProps":{"rk":false}}}


In backend I did this to finish registration

private int finishClientRegister(String credentialJSONString) {
		
	    try {
	        // Convert the JSON string to a PublicKeyCredential object
	        ObjectMapper mapper = new ObjectMapper();
	        PublicKeyCredential<AuthenticatorAttestationResponse, ClientRegistrationExtensionOutputs> credential = mapper.readValue(
	            credentialJSONString, 
	            new TypeReference<PublicKeyCredential<AuthenticatorAttestationResponse, ClientRegistrationExtensionOutputs>>() {}
	        );

	        // finish registration
	        RegistrationResult registrationResult = rp.finishRegistration(
	            FinishRegistrationOptions.builder()
	                .request(options) // Options from startRegistration step
	                .response(credential)
	                .build()
	        );





But I have java.lang.NullPointerException in line RegistrationResult registrationResult = rp.finishRegistration(...

The error doesn't give me any information about the reason.

If I remove the clientExtensionResults from the json I have the error
Cannot construct instance of `com.yubico.webauthn.data.PublicKeyCredential`, problem: clientExtensionResults is marked non-null but is null

**Comment by emlun** [comment]
> But I have java.lang.NullPointerException in line RegistrationResult registrationResult = rp.finishRegistration(...
> 
> The error doesn't give me any information about the reason.

Please provide the error message and stack trace anyway so that we can investigate it.

You should also use `PublicKeyCredential.parseRegistrationResponseJson(credentialJSONString)` instead of using your own `ObjectMapper`. `parseRegistrationResponseJson(String)` is the officially supported deserialization method. We cannot guarantee that using an external `ObjectMapper` will always continue to work - in case we need to change some internal (de)serialization mappings, for example.

**Comment by ericteles54hotmail** [comment]
Hello emlun

I did the change using PublicKeyCredential.parseRegistrationResponseJson(credentialJSONString) as you suggested. But I still have NullPointerException

private int finishClientRegister(String credentialJSONString) {
  try {
    RegistrationResult registrationResult = rp.finishRegistration(
	            FinishRegistrationOptions.builder()
	                .request(options) // Options from startRegistration step
	                .response(PublicKeyCredential.parseRegistrationResponseJson(credentialJSONString))
	                .build()
	        );
	       
The error occurs on the line
.response(PublicKeyCredential.parseRegistrationResponseJson(credentialJSONString))

This is the stack of error message when I had NullPointerException
java.lang.NullPointerException
at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.novell.nidp.servlets.filters.xss.XSSDetectionFilter.doFilter(y:2506)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.novell.nidp.servlets.filters.jsp.SameOriginFramingFilter.doFilter(y:2547)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.novell.nidp.servlets.filters.RequestResponseHook.doFilter(y:970)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        
        
        
       I tried to change my javascript to send the credential direct to server
       
       async function createCredential(options) {
					try {
						const publicKeyOptions = options.publicKey || options;
						const credential = await navigator.credentials.create({ publicKey: convertOptions(publicKeyOptions) });
						// Set the value of the hidden input field with the credential
						document.getElementById('passkeyCred').value = credential;
						// Submit the form
						document.RegisterForm.submit();
					
					} catch (error) {
						console.error("Error creating credential:", error);
					}
				}
        
        But in this way I had this error: 
        
        com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `com.yubico.webauthn.data.PublicKeyCredential<com.yubico.webauthn.data.AuthenticatorAttestationResponse,com.yubico.webauthn.data.ClientRegistrationExtensionOutputs>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"[object PublicKeyCredential]"; line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1520)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1467)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:648)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:211)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3660)
        at com.yubico.webauthn.data.PublicKeyCredential.parseRegistrationResponseJson(PublicKeyCredential.java:236        
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.novell.nidp.servlets.filters.xss.XSSDetectionFilter.doFilter(y:2506)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.novell.nidp.servlets.filters.jsp.SameOriginFramingFilter.doFilter(y:2547)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.novell.nidp.servlets.filters.RequestResponseHook.doFilter(y:970)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:750)
        
        
        
I'm a little confused about how the whole process should occur. These are the important parts of the code I'm using.

How should the options be generated in the backend and sent to the frontend
```
RelyingPartyIdentity rpIdentity = RelyingPartyIdentity.builder()
			    .id("mytestdomain.com")
			    .name("My First Example Application")
			    .build();

		RelyingParty rp = RelyingParty.builder()
		    .identity(rpIdentity)
		    .credentialRepository(new MyCredentialRepository(dbConnection))
		    .build();
		
		// Create UserIdentity
	    UserIdentity userIdentity = UserIdentity.builder()
	            .name(username)
	            .displayName("Display name - " + username)
	            .id(new ByteArray(UUID.randomUUID().toString().getBytes()))
	            .build();
		
		PublicKeyCredentialCreationOptions request = rp.startRegistration(
				  StartRegistrationOptions.builder()
				    .user(userIdentity)
				    .timeout(60000)
				    .authenticatorSelection(AuthenticatorSelectionCriteria.builder()				    		
				    		.userVerification(UserVerificationRequirement.DISCOURAGED)
				    		.authenticatorAttachment(AuthenticatorAttachment.CROSS_PLATFORM)
				    		.build())
				    .build());
```


How does the frontend receive the options, create the credential and send to server
  ```
<% String optionsAuth = (String) request.getAttribute("optionsAuth");  %>
  
  <script>
  const optionsJsonString = '<%=optionsAuth%>';
  const publicKeyCredentialCreationOptions = JSON.parse(optionsJsonString);
  
   async function createCredential(options) {
     try {
       const publicKeyOptions = options.publicKey || options;
       const credential = await navigator.credentials.create({ publicKey: convertOptions(publicKeyOptions) });
	// Set the value of the hidden input field with the credential
	document.getElementById('passkeyCred').value = credential;
	// Submit the form
	document.RegisterForm.submit();
      } catch (error) {
	 console.error("Error creating credential:", error);
      }
    }
  
  async function register() {
    const credential = await createCredential(publicKeyCredentialCreationOptions);
  </script>
  
  
  document.addEventListener("DOMContentLoaded", function() {
      // Start the registration process
     register();
   });
```

How does the server finalize the registration

```
private int finishClientRegister(String credentialJSONString) {
  try {
    RegistrationResult registrationResult = rp.finishRegistration(
	            FinishRegistrationOptions.builder()
	                .request(options) // Options from startRegistration step
	                .response(PublicKeyCredential.parseRegistrationResponseJson(credentialJSONString))
	                .build()
	        );
   }  catch (RegistrationFailedException e) {
      e.printStackTrace();
   }
 }      
```

**Comment by emlun** [comment]
Ok, that stack trace indeed doesn't seem to help much.

Anyway, I agree it looks like your problems are caused by your issues with encoding requests to and decoding responses from JSON. For example, what your `document.getElementById('passkeyCred').value = credential;` ends up doing is send the string `"[object PublicKeyCredential]"` to the server, instead of the inteded JSON structure.

Have you tried following the steps in the [Getting Started guide](https://github.com/Yubico/java-webauthn-server?tab=readme-ov-file#getting-started), and using GitHub's [webauthn-json](https://github.com/github/webauthn-json) library for handling the JSON encoding?

**Comment by ericteles54hotmail** [comment]
I haven't tried using the webauthn-json library yet, I'll try to do some testing with it to see if it works. It seems like it's an issue with the format of the json that's arriving at the backend to finish the registration.
