### ISSUE TITLE
Failed to parse extension data

### ISSUE THREAD

**Issue by tarun14110** [Yubico/java-webauthn-server#68]
I am using [](https://github.com/Yubico/libfido2) to communicate with my yubico security key and then register at the demo website on my local machine. I am using `fido_cred_set_extensions(cred, 0);` and is getting the below error. When I try to set extension flag to False by using `fido_cred_set_extensions(cred, FIDO_OPT_FALSE)`, I get error `fido_makecred: FIDO_ERR_UNSUPPORTED_OPTION (0x2b) `. Can someone help me find the source of this issue?

```
 Task :webauthn-server-demo:run
10:05:59.263-0600 [main] DEBUG demo.webauthn.Config - YUBICO_WEBAUTHN_ALLOWED_ORIGINS: null
10:05:59.264-0600 [main] INFO  demo.webauthn.Config - Origins: [https://localhost:8443]
10:05:59.265-0600 [main] DEBUG demo.webauthn.Config - RP name: null
10:05:59.265-0600 [main] DEBUG demo.webauthn.Config - RP ID: null
10:05:59.265-0600 [main] DEBUG demo.webauthn.Config - RP icon: null
10:05:59.265-0600 [main] DEBUG demo.webauthn.Config - RP name not given - using default.
10:05:59.265-0600 [main] DEBUG demo.webauthn.Config - RP ID not given - using default.
10:05:59.265-0600 [main] DEBUG demo.webauthn.Config - RP icon not given - using none.
10:05:59.265-0600 [main] INFO  demo.webauthn.Config - RP identity: RelyingPartyIdentity(name=Yubico WebAuthn demo, id=localhost, icon=Optional.empty)
10:05:59.265-0600 [main] DEBUG demo.webauthn.Config - YUBICO_WEBAUTHN_U2F_APPID: null
10:05:59.267-0600 [main] DEBUG demo.webauthn.Config - U2F AppId: https://localhost:8443
10:05:59.706-0600 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @581ms to org.eclipse.jetty.util.log.Slf4jLog
10:05:59.750-0600 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.9.v20180320; built: 2018-03-20T06:21:10-06:00; git: 1f8159b1e4a42d3f79997021ea1609f2fbac6de5; jvm 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09
Jun 05, 2020 10:05:59 AM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider demo.webauthn.WebAuthnRestResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider demo.webauthn.WebAuthnRestResource will be ignored. 
10:06:00.069-0600 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@407cf41{/,file:///home/tarun/Desktop/U2Fproject/java-webauthn-server/webauthn-server-demo/src/main/webapp/,AVAILABLE}
10:06:00.079-0600 [main] INFO  o.e.jetty.util.ssl.SslContextFactory - x509=X509@37cd92d6(serverkey,h=[],w=[]) for SslContextFactory@5922ae77[provider=null,keyStore=file:///home/tarun/Desktop/U2Fproject/java-webauthn-server/webauthn-server-demo/keystore.jks,trustStore=null]
10:06:00.106-0600 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@2d72f75e{SSL,[ssl, http/1.1]}{127.0.0.1:8443}
10:06:00.107-0600 [main] INFO  org.eclipse.jetty.server.Server - Started @982ms
10:07:00.688-0600 [qtp1561063579-12] DEBUG demo.webauthn.WebAuthnRestResource - startRegistration JSON response: {"success":true,"request":{"username":"a2","credentialNickname":"a2","requestId":"aCSTdchg8Aio40iNc7PHjqRtBVP0Zva7we3vngoc-v4","publicKeyCredentialCreationOptions":{"rp":{"name":"Yubico WebAuthn demo","id":"localhost"},"user":{"name":"a2","displayName":"a2","id":"zPJ66TIw5KXDizs3DIv24pmu5g7oRTgAVPcIP6ehACY"},"challenge":"Zd2TLJ1pkVEPimqxg0Pzgv6zLNT5n_gTNsc5QyzUIqE","pubKeyCredParams":[{"alg":-7,"type":"public-key"},{"alg":-8,"type":"public-key"},{"alg":-257,"type":"public-key"}],"excludeCredentials":[],"authenticatorSelection":{"requireResidentKey":false,"userVerification":"preferred"},"attestation":"direct","extensions":{}},"sessionToken":"-S9B9RXwWf5JyLMXC3RjHnJ3dXsZzu1-YC2g2izLbV8"},"actions":{"finish":"https://localhost:8443/api/v1/register/finish","finishU2f":"https://localhost:8443/api/v1/register/finish-u2f"}}
10:07:02.555-0600 [qtp1561063579-27] ERROR demo.webauthn.WebAuthnServer - JSON error in finishRegistration; responseJson: {"requestId":"aCSTdchg8Aio40iNc7PHjqRtBVP0Zva7we3vngoc-v4","credential":{"type":"public-key","id":"ZdXr6LLJmSy1z8JANc_q2_PqsgRDP74l3tuDbZny1F2OmGeSO1N4zVvDXh0pB45vtK6uPc7A4_ib7-H7PVfBiw","response":{"attestationObject":"o2NmbXRmcGFja2VkaGF1dGhEYXRhWMZYxEmWDeWIDoxodDQXD2R2YFuP5K65ooYyx5lc87qDHZdjQQAAAAAAAAAAAAAAAAAAAAAAAAAAAEBl1evossmZLLXPwkA1z-rb8-qyBEM_viXe24NtmfLUXY6YZ5I7U3jNW8NeHSkHjm-0rq49zsDj-Jvv4fs9V8GLpQECAyYgASFYIEfu_XVdZ4hoPuA3T483n4NM3MJw_GK75tEI_FAqdr41Ilgg8shTi12jh_uy5Jjz9UEZbIcMwvVV7CQKrCPsevlpS7BnYXR0U3RtdKNjYWxnJmNzaWdYRzBFAiEAxEAmO0Jl3beBHUMdy1zu4tvfOGV8tCrpsZpIj5FzNa4CIBpVNxOqa3QwjL7prUGMcFc6KCS6MKcTI4kK0tlW75e1Y3g1Y4FZAlMwggJPMIIBN6ADAgECAgQq2WrzMA0GCSqGSIb3DQEBCwUAMC4xLDAqBgNVBAMTI1l1YmljbyBVMkYgUm9vdCBDQSBTZXJpYWwgNDU3MjAwNjMxMCAXDTE0MDgwMTAwMDAwMFoYDzIwNTAwOTA0MDAwMDAwWjAxMS8wLQYDVQQDDCZZdWJpY28gVTJGIEVFIFNlcmlhbCAyMzkyNTczNDUxNjU1MDM4NzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABC_hoj6_pVs-Rh1ZpDUi15dImBy6bSiamPG9ff9lZoDbu-28K65gfm73cvV2sE1UxOXzL1lvJuYRFccnLPbKdZSjOzA5MCIGCSsGAQQBgsQKAgQVMS4zLjYuMS40LjEuNDE0ODIuMS4yMBMGCysGAQQBguUcAgEBBAQDAgQwMA0GCSqGSIb3DQEBCwUAA4IBAQCFavqLz08_Yl8pG8EVjjx-vSVSvPdXB1P1Eh2mpU0kzM-uJ87WqzESjCl-W1uJBd2gIBeTHx9fWSWTWVH8AEvL4grdfY0FL5VDs0lsFbgxDhDL2bsFOCdPWD6tH0USiMPqdtBwrUTlOv6o8i0fc2Jf8tWJ_jDfJmLLfLt8mWGArc-pik0BLPMTRs0RdGpYSOi-7fPjDMvZwd0iFnGyg4hh9lpFNiO1GNVWf6jwo84QXfTxOVPhFOpZ4Kfy_maIZ0MuUv1qL2T3PEjNmzjy37oseks7ESjfJtZqJPiV3aC2EYD0FE9rcHXDGKSa4ItY02rbHjBTZysXxaGffwoi8Q6U","clientDataJSON":"ewoJImNoYWxsZW5nZSIgOiAiWmQyVExKMXBrVkVQaW1xeGcwUHpndjZ6TE5UNW5fZ1ROc2M1UXl6VUlxRSIsCgkib3JpZ2luIiA6ICJodHRwczovL2xvY2FsaG9zdDo4NDQzIiwKCSJ0eXBlIiA6ICJ3ZWJhdXRobi5jcmVhdGUiCn0"},"clientExtensionResults":{}},"sessionToken":"-S9B9RXwWf5JyLMXC3RjHnJ3dXsZzu1-YC2g2izLbV8"}
com.upokecenter.cbor.CBORException: Too many bytes
        at com.upokecenter.cbor.CBORObject.CheckCBORLength(CBORObject.java:5644)
        at com.upokecenter.cbor.CBORObject.DecodeFromBytes(CBORObject.java:890)
        at com.upokecenter.cbor.CBORObject.DecodeFromBytes(CBORObject.java:766)
        at com.yubico.webauthn.data.AuthenticatorData.parseExtensions(AuthenticatorData.java:231)
        ... 84 common frames omitted
Wrapped by: java.lang.IllegalArgumentException: Failed to parse extension data
        at com.yubico.webauthn.data.AuthenticatorData.parseExtensions(AuthenticatorData.java:233)
        at com.yubico.webauthn.data.AuthenticatorData.<init>(AuthenticatorData.java:133)
        at com.yubico.webauthn.data.AttestationObject.<init>(AttestationObject.java:167)
        at com.yubico.webauthn.data.AuthenticatorAttestationResponse.<init>(AuthenticatorAttestationResponse.java:96)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
        ... 75 common frames omitted
Wrapped by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.yubico.webauthn.data.AuthenticatorAttestationResponse`, problem: Failed to parse extension data
 at [Source: (String)"{"requestId":"aCSTdchg8Aio40iNc7PHjqRtBVP0Zva7we3vngoc-v4","credential":{"type":"public-key","id":"ZdXr6LLJmSy1z8JANc_q2_PqsgRDP74l3tuDbZny1F2OmGeSO1N4zVvDXh0pB45vtK6uPc7A4_ib7-H7PVfBiw","response":{"attestationObject":"o2NmbXRmcGFja2VkaGF1dGhEYXRhWMZYxEmWDeWIDoxodDQXD2R2YFuP5K65ooYyx5lc87qDHZdjQQAAAAAAAAAAAAAAAAAAAAAAAAAAAEBl1evossmZLLXPwkA1z-rb8-qyBEM_viXe24NtmfLUXY6YZ5I7U3jNW8NeHSkHjm-0rq49zsDj-Jvv4fs9V8GLpQECAyYgASFYIEfu_XVdZ4hoPuA3T483n4NM3MJw_GK75tEI_FAqdr41Ilgg8shTi12jh_uy5Jjz9UEZbIcMwvVV"[truncated 1228 chars]; line: 1, column: 1637] (through reference chain: demo.webauthn.data.RegistrationResponse["credential"]->com.yubico.webauthn.data.PublicKeyCredential["response"])
        at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1754)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:491)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:514)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285)
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:424)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1310)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:535)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:419)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1310)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:535)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:419)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1310)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
        at demo.webauthn.WebAuthnServer.finishRegistration(WebAuthnServer.java:325)
        at demo.webauthn.WebAuthnRestResource.finishRegistration(WebAuthnRestResource.java:187)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:864)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:291)
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:151)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
        at java.lang.Thread.run(Thread.java:748)
10:07:02.555-0600 [qtp1561063579-27] DEBUG demo.webauthn.WebAuthnRestResource - fail finishRegistration responseJson: {"requestId":"aCSTdchg8Aio40iNc7PHjqRtBVP0Zva7we3vngoc-v4","credential":{"type":"public-key","id":"ZdXr6LLJmSy1z8JANc_q2_PqsgRDP74l3tuDbZny1F2OmGeSO1N4zVvDXh0pB45vtK6uPc7A4_ib7-H7PVfBiw","response":{"attestationObject":"o2NmbXRmcGFja2VkaGF1dGhEYXRhWMZYxEmWDeWIDoxodDQXD2R2YFuP5K65ooYyx5lc87qDHZdjQQAAAAAAAAAAAAAAAAAAAAAAAAAAAEBl1evossmZLLXPwkA1z-rb8-qyBEM_viXe24NtmfLUXY6YZ5I7U3jNW8NeHSkHjm-0rq49zsDj-Jvv4fs9V8GLpQECAyYgASFYIEfu_XVdZ4hoPuA3T483n4NM3MJw_GK75tEI_FAqdr41Ilgg8shTi12jh_uy5Jjz9UEZbIcMwvVV7CQKrCPsevlpS7BnYXR0U3RtdKNjYWxnJmNzaWdYRzBFAiEAxEAmO0Jl3beBHUMdy1zu4tvfOGV8tCrpsZpIj5FzNa4CIBpVNxOqa3QwjL7prUGMcFc6KCS6MKcTI4kK0tlW75e1Y3g1Y4FZAlMwggJPMIIBN6ADAgECAgQq2WrzMA0GCSqGSIb3DQEBCwUAMC4xLDAqBgNVBAMTI1l1YmljbyBVMkYgUm9vdCBDQSBTZXJpYWwgNDU3MjAwNjMxMCAXDTE0MDgwMTAwMDAwMFoYDzIwNTAwOTA0MDAwMDAwWjAxMS8wLQYDVQQDDCZZdWJpY28gVTJGIEVFIFNlcmlhbCAyMzkyNTczNDUxNjU1MDM4NzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABC_hoj6_pVs-Rh1ZpDUi15dImBy6bSiamPG9ff9lZoDbu-28K65gfm73cvV2sE1UxOXzL1lvJuYRFccnLPbKdZSjOzA5MCIGCSsGAQQBgsQKAgQVMS4zLjYuMS40LjEuNDE0ODIuMS4yMBMGCysGAQQBguUcAgEBBAQDAgQwMA0GCSqGSIb3DQEBCwUAA4IBAQCFavqLz08_Yl8pG8EVjjx-vSVSvPdXB1P1Eh2mpU0kzM-uJ87WqzESjCl-W1uJBd2gIBeTHx9fWSWTWVH8AEvL4grdfY0FL5VDs0lsFbgxDhDL2bsFOCdPWD6tH0USiMPqdtBwrUTlOv6o8i0fc2Jf8tWJ_jDfJmLLfLt8mWGArc-pik0BLPMTRs0RdGpYSOi-7fPjDMvZwd0iFnGyg4hh9lpFNiO1GNVWf6jwo84QXfTxOVPhFOpZ4Kfy_maIZ0MuUv1qL2T3PEjNmzjy37oseks7ESjfJtZqJPiV3aC2EYD0FE9rcHXDGKSa4ItY02rbHjBTZysXxaGffwoi8Q6U","clientDataJSON":"ewoJImNoYWxsZW5nZSIgOiAiWmQyVExKMXBrVkVQaW1xeGcwUHpndjZ6TE5UNW5fZ1ROc2M1UXl6VUlxRSIsCgkib3JpZ2luIiA6ICJodHRwczovL2xvY2FsaG9zdDo4NDQzIiwKCSJ0eXBlIiA6ICJ3ZWJhdXRobi5jcmVhdGUiCn0"},"clientExtensionResults":{}},"sessionToken":"-S9B9RXwWf5JyLMXC3RjHnJ3dXsZzu1-YC2g2izLbV8"}
10:07:02.555-0600 [qtp1561063579-27] DEBUG demo.webauthn.WebAuthnRestResource - Encoding messages as JSON: [Registration failed!, Failed to decode response object., Cannot construct instance of `com.yubico.webauthn.data.AuthenticatorAttestationResponse`, problem: Failed to parse extension data
 at [Source: (String)"{"requestId":"aCSTdchg8Aio40iNc7PHjqRtBVP0Zva7we3vngoc-v4","credential":{"type":"public-key","id":"ZdXr6LLJmSy1z8JANc_q2_PqsgRDP74l3tuDbZny1F2OmGeSO1N4zVvDXh0pB45vtK6uPc7A4_ib7-H7PVfBiw","response":{"attestationObject":"o2NmbXRmcGFja2VkaGF1dGhEYXRhWMZYxEmWDeWIDoxodDQXD2R2YFuP5K65ooYyx5lc87qDHZdjQQAAAAAAAAAAAAAAAAAAAAAAAAAAAEBl1evossmZLLXPwkA1z-rb8-qyBEM_viXe24NtmfLUXY6YZ5I7U3jNW8NeHSkHjm-0rq49zsDj-Jvv4fs9V8GLpQECAyYgASFYIEfu_XVdZ4hoPuA3T483n4NM3MJw_GK75tEI_FAqdr41Ilgg8shTi12jh_uy5Jjz9UEZbIcMwvVV"[truncated 1228 chars]; line: 1, column: 1637] (through reference chain: demo.webauthn.data.RegistrationResponse["credential"]->com.yubico.webauthn.data.PublicKeyCredential["response"])]
```

**Comment by emlun** [comment]
Hi! Did you mean to say you're using [libfido2](https://github.com/Yubico/libfido2) to communicate with the YubiKey? I think you'll need to move the questions about the libfido2 API to there.

Either way, it seems like the authenticator data that gets returned is corrupted. You can find the attestation object in the stacktrace; the [authenticator data](https://www.w3.org/TR/2019/WD-webauthn-2-20191126/#sctn-authenticator-data) is:

```
58C449960DE5880E8C687434170F6476605B8FE4AEB9A28632C7995CF3BA831D  # RP ID hash?
97                                                                # Flags: UP, RFU1, UV, RFU2-4, ED (corrupted)
63410000                                                          # Signature counter (corrupted)
000000000000000000000000000000000000004065D5EBE8B2C9992CB5CFC240  # Garbage, as far as I can tell
35CFEADBF3EAB204433FBE25DEDB836D99F2D45D8E9867923B5378CD5BC35E1D
29078E6FB4AEAE3DCEC0E3F89BEFE1FB3D57C18BA501020326200121582047EE
FD755D6788683EE0374F8F379F834CDCC270FC62BBE6D108FC502A76BE352258
20F2C8538B5DA387FBB2E498F3F541196C870CC2F555EC240AAC23EC7AF9694B
B0
```

The rest of the attestation object seems well-formed.

**Comment by tarun14110** [comment]
Thanks @emlun. Closing the issue here.

**Comment by tarun14110** [comment]
@emlun I'm sorry, but I couldn't find the authenticator data that you wrote in my stack trace. Did you process the attestation object from stacktrace?

**Comment by emlun** [comment]
Yes, the authenticator data is embedded in the attestation object. You can for example put that into [cbor.me](https://cbor.me) if you first do a bit of roundabout to convert it from base64url to hex (in a Unix-like terminal you can do this via `echo '<attestation object base64url>' | tr '_-' '/+' | base64 -d | xxd -p`). It'll parse the attestation object and you can get the authenticator data (in hex) from there.
